-- MySQL Script generated by MySQL Workbench
-- jue 04 ene 2024 20:29:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academic_software
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `academic_software` ;

-- -----------------------------------------------------
-- Schema academic_software
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academic_software` ;
USE `academic_software` ;

-- -----------------------------------------------------
-- Table `academic_software`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academic_software`.`table1` ;

CREATE TABLE IF NOT EXISTS `academic_software`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academic_software`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academic_software`.`role` ;

CREATE TABLE IF NOT EXISTS `academic_software`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academic_software`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `academic_software`.`user` ;

CREATE TABLE IF NOT EXISTS `academic_software`.`user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(75) NOT NULL,
  `last_name` VARCHAR(75) NOT NULL,
  `role` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`username`),
  INDEX `fk_USER_ROLE_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ROLE`
    FOREIGN KEY (`role`)
    REFERENCES `academic_software`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
